### PR TITLE
Issue 225

### LINKED ISSUE #225: Refactor dead code

### PR DESCRIPTION
**Pull request by Adoni5**
Closes #225 

Refactoring dead code as part of the issue_218 effort. I'm sure this won't somehow resolve into epic merge conflicts later....
loljks it definitely will!

### CODE REVIEW

**Comment by Adoni5** [comment]
Too scared to black validate.py and add it as it's own commit

**Comment by alexomics** [comment]
Fix lints for merge

**Review by alexomics — CHANGES_REQUESTED** [review]
Fix lints lol

**Comment by Adoni5** [comment]
Closing as most of this is in the updated branches

**Pull request closed without merging**
